---
  name: deploy
  
  on:
    push:
      tags:
        - '*'
  
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Install node  
          uses: actions/setup-node@v4
          with:
            node-version: 20
  
        - name: Install dependencies
          run: npm ci -f
  
        - name: Build
          run: npm run build
  
        - uses: JS-DevTools/npm-publish@v3
          with:
            token: ${{ secrets.NPM_TOKEN }}
            access: "public"